    <?xml version="1.0" encoding="UTF-8"?>
    <xsl:stylesheet version="1.0"
                    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                    xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                    exclude-result-prefixes="sitemap">

    <xsl:output method="html" encoding="UTF-8" indent="yes"/>

    <xsl:template match="/">
      <html>
        <head>
          <title>XML Sitemap</title>
          <style type="text/css">
            body { font-family: Helvetica, Arial, sans-serif; font-size: 13px; color: #545454; }
            table { border: none; border-collapse: collapse; width: 100%; }
            th { text-align: left; padding: 5px; border-bottom: 1px solid #ccc; }
            td { padding: 5px; border-bottom: 1px solid #eee; }
            td a { color: #007AFF; }
            td a:hover { text-decoration: underline; }
            thead th { background-color: #f8f8f8; }
          </style>
        </head>
        <body>
          <h1>XML Sitemap</h1>
          <p>Generated by RTBRuhan. This is an XML sitemap, primarily meant for search engines.</p>
          <table>
            <thead>
              <tr>
                <th>URL</th>
                <th>Last Modified</th>
                <th>Change Frequency</th>
                <th>Priority</th>
              </tr>
            </thead>
            <tbody>
              <xsl:apply-templates select="sitemap:urlset/sitemap:url"/>
            </tbody>
          </table>
        </body>
      </html>
    </xsl:template>

    <xsl:template match="sitemap:url">
      <tr>
        <td>
          <xsl:variable name="loc" select="sitemap:loc"/>
          <a href="{$loc}"><xsl:value-of select="sitemap:loc"/></a>
        </td>
        <td><xsl:value-of select="sitemap:lastmod"/></td>
        <td><xsl:value-of select="sitemap:changefreq"/></td>
        <td><xsl:value-of select="sitemap:priority"/></td>
      </tr>
    </xsl:template>

    </xsl:stylesheet>